---
- import_playbook: in-memory-inventory.yml

- name: Play to automate process
  hosts: controls
  gather_facts: false
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      #delegate_facts: true
      delegate_to: localhost
      connection: ssh
      register: local_facts

    - name: Print Log
      debug: 
        msg: "{{ local_facts.ansible_facts.ansible_default_ipv4.address }}"

    - name: Create File
      copy:
        content: |
          dns1: "{{ local_facts.ansible_facts.ansible_default_ipv4.address }}" 
        dest: ./dns_server.yml


- name: Play Import and Print DNS Server IP
  hosts: localhost
  gather_facts: false
  vars_files:
    - dns_server.yml
  tasks:
    - name: Print DNS Server
      debug:
        msg: "{{ dns1 }}"
