---
#- import_playbook: in-memory-inventory.yml

- name: Create OpenStack Instances
  hosts: controls 
  connection: ssh
  gather_facts: false
  tasks:
    - include_role:
        name: infra
        tasks_from: main
