---
- import_playbook: in-memory-inventory.yml

- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
  roles:
    - database
