- name: Remove OpenStack Instances
  hosts: controls
  connection: ssh 
  gather_facts: false
  collections:
    - openstack
  tasks:
    - include_role:
         name: infra
         tasks_from: destroy
