
- name: Play to automate process
  hosts: localhost
  gather_facts: false
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      #delegate_facts: true
      delegate_to: localhost
      connection: ssh
      register: champ023

    - name: Print
      debug: 
        msg: "{{ champ023.ansible_facts.ansible_default_ipv4.address }}"

    - name: Create File
      copy:
        content: |
          frontend1: "192.168.1.1" 
          app: "192.168.1.20"
        dest: ./dns_server.yml
