- name: Play Test
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    guid: "{{ lookup('ENV','GUID') }}"
    jom: "{{ lookup('ENV','JOM') }}"
  tasks:
    - name: Print Fact
      debug:
        var=ansible_facts 

    - name: Print GUID
      debug:
        var=guid

    - name: Print JOM
      debug:
        var=jom

