
- name: Play to automate process
  hosts: localhost
  gather_facts: false
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      #delegate_facts: true
      delegate_to: localhost
      connection: ssh
      register: champ023

    - name: Print
      debug: var=champ023
