---
- import_playbook: in-memory-inventory.yml

- name: Teardown Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false
  vars:
    postgres_rhel8_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    postgres_packages:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
    postgres_library: "python3-psycopg2"
    postgres_data_dir: /var/lib/pgsql/data
    postgres_port: 5432

  tasks:

    - name: Remove Postgres packages
      package:
        name: "{{ __package }}"
        state: absent
      loop:
        #- "{{ postgres_rhel8_repo }}"
        - "{{ postgres_library }}"
        - "{{ postgres_packages }}"
      loop_control:
        loop_var: __package

    - name: Remove Postgres 12 data directory
      file:
        path: /var/lib/pgsql/
        state: absent

    - name: Remove Postgres user
      user:
        name: postgres
        state: absent
