---
# defaults file for roles/infra
#guid: "{{ lookup('ENV','GUID') }}"

instances:
  - name: frontend1
    keypair: "{{ guid }}-keypair"
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: "{{ guid }}-HostSG"
    internal_network: "{{ guid }}-dev-network"
    metadata:
      AnsibleGroup: load_balancers
      deployment_name: dev

#  - name: app1
#    keypair: "{{ guid }}-keypair"
#    image: rhel-8.3
#    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
#    security_group: "{{ guid }}-HostSG"
#    internal_network: "{{ guid }}-dev-network"
#    metadata:
#      AnsibleGroup: app_servers
#      deployment_name: dev

#  - name: app2
#    keypair: "{{ guid }}-keypair"
#    image: rhel-8.3
#    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
#    security_group: "{{ guid }}-HostSG"
#    internal_network: "{{ guid }}-dev-network"
#    metadata:
#      AnsibleGroup: app_servers
#      deployment_name: dev

#  - name: appdb1
#    keypair: "{{ guid }}-keypair"
#    image: rhel-8.3
#    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
#    security_group: "{{ guid }}-HostSG"
#    internal_network: "{{ guid }}-dev-network"
#    metadata:
#      AnsibleGroup: database_servers
#      deployment_name: dev
